name: Continuous integration and delivery
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  ci-cd:
    uses: Calance-US/calance-workflows/.github/workflows/build.yml@v1.0.3

  deploy-to-kubernetes:
    needs: ci-cd
    uses: Calance-US/calance-workflows/.github/workflows/deploy.yml@v1.0.3
    with:
      repository_name: ${{ github.event.repository.name }}
      version: ${{ needs.ci-cd.outputs.version }}
      cluster_environment: ${{ needs.ci-cd.outputs.cluster_environment }}
    secrets:
      NAMESPACE: ${{ secrets.NAMESPACE }}
      JENKINS_URL: ${{ secrets.JENKINS_URL }}
      JENKINS_USER: ${{ secrets.JENKINS_USER }}
      JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
