name: TestCase 1 - Testing the working of action
on:
  push:
    branches:
      - "408-get-url-of-packages"
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (clone the repo for use)
        uses: actions/checkout@v3
      - uses: Calance-US/calance-get-packages-url-action@408-get-url-of-packages
        id: get-packages-url
        with:
          packages_failed_to_delete: 'calance-workflows:59559826,calance-workflows:79627191,calance-services:98765432'
          packages_needs_github_assistance: 'calance-services:1234567,calance-services:79627191'
      - name: Echo the outputs
        run: |
          
          echo ${{ steps.get-packages-url.outputs.packages_needs_github_assistance_urls}}
